### ISSUE TITLE
New Business Goal is placed.

### ISSUE THREAD

**Issue by jose598** [karinaortega1507/ISII-WORKSHOPS-MARKETING_DIGITAL#4] opened 2022-01-15 02:27 UTC
Dear support team, we are satisfied about your hard work during this last year. On this new year we want to be bigger and better. In the meeting with the Accounting Department and Business Intelligent Group, we proposed some changes with the intention of improving our service and getting more customers. The new business rule establishes: If the customer is married and has more than 30 years old but younger than 60, then $50 must be decreased to the base premium for each one, however if the customer is single, woman and older than 60 years old , she will receive a discount for around $50.

You need to know that all rules should be maintained how it was coming. Our request should be added to the existing one and the result should be calculated with all rules applied.

**Comment by karinaortega1507** [comment] 2022-01-15 05:21
The issue has been reproduced

**Comment by karinaortega1507** [comment] 2022-01-15 05:23
I have proceeded to categorize the issue

**Comment by karinaortega1507** [comment] 2022-01-15 05:29
I have proceeded to process the request. @EdwinEras  will be the assigned analyst and @tomdbelt  will develop the solution and @EdwinEras will perform the tests

**Comment by jose598** [comment] 2022-01-15 16:24
Thank you @karinaortega1507. I'm waiting for your answer...

**Comment by EdwinEras** [comment] 2022-01-15 23:19
Impact analysis. We need to modify the function premiumCalculation in CarInsurance.java file and add two new conditionals. The time estimated to perform changes are 30 minutes, to solve the problems 30 minutes and to test the issue 1 hour. Changes do not affect other parts of the program

[Issue Management - MARKETING DIGITAL.docx](https://github.com/karinaortega1507/ISII-WORKSHOPS-MARKETING_DIGITAL/files/7876058/Issue.Management.-.MARKETING.DIGITAL.docx)
#documentation  #Impact analysis

**Comment by jose598** [comment] 2022-01-16 00:05
Hi @EdwinEras  I'd like to know if you can send me a table with all cases applied, this one is for getting information about how the prima is going to be calculated, also it's important for us know if you will need to use our computers or not and how long? 

No forget that the request have different cases and discount is applied depend of it. 

Thank you!.

**Comment by EdwinEras** [comment] 2022-01-16 01:09
Hi @jose598, the file now contains two tables, one with equivalence classes and other with test cases using boundary value approach for tests. The new two tables do no contains the new business logic test cases because the issue is not cover yet.

[Issue Management - MARKETING DIGITAL.docx](https://github.com/karinaortega1507/ISII-WORKSHOPS-MARKETING_DIGITAL/files/7876185/Issue.Management.-.MARKETING.DIGITAL.docx)

**Comment by EdwinEras** [comment] 2022-01-16 01:11
#impact analysis #help wanted

**Comment by EdwinEras** [comment] 2022-01-16 01:12
> Hi @jose598, the file now contains two tables, one with equivalence classes and other with test cases using boundary value approach for tests. The new two tables do no contains the new business logic test cases because the issue is not cover yet.
> 
> [Issue Management - MARKETING DIGITAL.docx](https://github.com/karinaortega1507/ISII-WORKSHOPS-MARKETING_DIGITAL/files/7876185/Issue.Management.-.MARKETING.DIGITAL.docx)

#Impact analysis #help wanted

**Comment by jose598** [comment] 2022-01-16 06:59
Thank you  @EdwinEras. All of you can start working with the issue request.

**Comment by tomdbelt** [comment] 2022-01-18 02:05
Hi all.

I have made the respective corrections to the premiumCalculation method adding the new system requirements.

I enclose the code of the method for your quick review and I remain at your service in case it is necessary to make any additional corrections.

Best regards,
Tommy Beltrán
Programmer

https://github.com/karinaortega1507/ISII-WORKSHOPS-MARKETING_DIGITAL/blob/69cc605f538063292dd5a242030b4fa9a26f8d90/ec.edu.espol.workshops/lib/src/main/java/ec/edu/espol/workshops/CarInsurance.java#L78-L92

**Comment by jose598** [comment] 2022-01-18 02:57
Hello Team, I was taking a look at your code and I think that you haven't considered people who have 30 and 60 years old. Otherwise, the discount is $100 when married because they got $50 for each one.

I confused on the request, please consider both ages as well.

Check it out again.

**Comment by tomdbelt** [comment] 2022-01-20 22:22
Hi @jose598 

Thank you very much for your observation. We have corrected the code once again. We hope that now it is as you need it. We also appreciate any additional suggestions.

https://github.com/karinaortega1507/ISII-WORKSHOPS-MARKETING_DIGITAL/blob/4ccc361698d4c77755dac190538ecfa85a25f8c2/ec.edu.espol.workshops/lib/src/main/java/ec/edu/espol/workshops/CarInsurance.java#L78-L92

**Comment by jose598** [comment] 2022-01-21 00:32
Thank you @tomdbelt . Please I need test plan

**Comment by EdwinEras** [comment] 2022-01-21 01:12
Hello @jose598 I did the tests for the program but I have questions about the final value of the prima, in the document I present the values that I hope and what the program returned, perhaps I expected the wrong values. Could you check if the returned values are correct please?
The new values are yellow highlighted. 

[Issue Management - MARKETING DIGITAL.docx](https://github.com/karinaortega1507/ISII-WORKSHOPS-MARKETING_DIGITAL/files/7909553/Issue.Management.-.MARKETING.DIGITAL.docx)

**Comment by EdwinEras** [comment] 2022-01-21 01:13
#Acceptance testing #bug

**Comment by jose598** [comment] 2022-01-21 21:39
Hi @EdwinEras I can't understand what values you are saying. 
Please tell me where.

**Comment by EdwinEras** [comment] 2022-01-21 23:11
Hi @jose598, the expected outputs and the actual outputs of the program. 
In this file there is only the test this workshop.

[Issues Management.docx](https://github.com/karinaortega1507/ISII-WORKSHOPS-MARKETING_DIGITAL/files/7917077/Issues.Management.docx)

**Comment by jose598** [comment] 2022-01-21 23:17
Ok now I got it.

I already approved this issue, thank you. 
Close this one please.

**Comment by karinaortega1507** [comment] 2022-01-22 02:18
Hi @jose598, the solution has been completed and the programmer will release the new software version for you.

Thank you

**Comment by jose598** [comment] 2022-01-22 02:19
@karinaortega1507 Got it

**Comment by tomdbelt** [comment] 2022-01-22 02:38
Hi @jose598 

The new version of the software is ready for use. In order to download it you need to perform the following steps:

1. Enter the Command Prompt on your computer and use the following command:
> git clone https://github.com/karinaortega1507/ISII-WORKSHOPS-MARKETING_DIGITAL.git 

Or if you want you can also download a zip of the entire repository through the following link https://github.com/karinaortega1507/ISII-WORKSHOPS-MARKETING_DIGITAL/archive/refs/heads/master.zip
If you do the latter, you must unzip the file.

2. In the same Command Prompt, go to the main repository folder and use the following command:
> git checkout IssuesManagement

With this command you access the new version of the system.

3. From an IDE like Eclipse, run the program as you did before.

There are no changes in the way the program works, so you are already familiar with its use. Only the requirements you have requested have been added.

We remain attentive to any questions about the installation. We hope you enjoy the new version of the software.

Sincerely,
Tommy Beltrán
CEO & Programmer

**Comment by jose598** [comment] 2022-01-22 02:45
Thank your @tomdbelt.
Everything works well.

**Comment by karinaortega1507** [comment] 2022-01-22 02:48
Dear @jose598 , thank you for confirming.

So, can we close this issue now?

**Comment by jose598** [comment] 2022-01-22 02:48
Yes @karinaortega1507. Go ahead :)
Thank your for solving my issue.

**Comment by karinaortega1507** [comment] 2022-01-22 02:50
Thanks to you @jose598 .

Greetings!!

**Closed as completed by karinaortega1507** 2022-01-22 02:50 UTC
Labels: documentation, enhancement, Issue reproduction, Issue categorization, Issue assignment, Impact analysis, Solve the issue, Test the solution, Acceptance testing, Completeness verification, Enactment of the solution, Follow up, Class 1 change
